# Generated by Django 5.1.4 on 2025-01-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biznews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_media',
            new_name='social_link',
        ),
    ]
